safe: true
lsi: false
pygments: true
exclude:
- 'bin'
- 'changelog.txt'
- 'CNAME'
- 'config.rb'
- 'docs'
- 'Gemfile'
- 'Gemfile.lock'
- 'Gruntfile.js'
- 'lib'
- 'package.json'
- 'Rakefile'
- 'README.md'
- 'sass'
- 'spec'
- 'templates'
permalink: pretty

mvp:
  number_of_projects: 65
